export const HOME = '/'
export const MENU = '/menu'
export const BOOK_TABLE = '/book-table'
export const REVIEW_BOOKING = '/review-booking'
export const LOGIN = '/login'
export const ADMIN = '/admin'
