export const fullProducts = [
  {
    id: 1,
    created_at: "2021-10-31T08:57:59",
    updated_at: "2020-02-15",
    name: "Tzatziki",
    description: "Refreshing traditional cucumber and garlic yogourt dip. Seasoned with fresh, local herbs.",
    price: 850,
    in_stock: true,
    sale: false,
    category_id: 2,
    category_name: "general",
  },
  {
    id: 2,
    created_at: "2021-10-31T10:13:10",
    updated_at: "2020-02-15",
    name: "Keftedakia",
    description: "Bite size, beef or lamb meatballs seasoned with fresh Greek herbs.",
    price: 1600,
    in_stock: true,
    sale: false,
    category_id: 2,
    category_name: "general",
  },
  {
    id: 3,
    created_at: "2021-10-31T10:32:07",
    updated_at: "2020-02-15",
    name: "Saganaki",
    description: "Fried traditional Greek cheese - Graviera with light hint of lemon and garlic.",
    price: 1500,
    in_stock: true,
    sale: false,
    category_id: 2,
    category_name: "general",
  },
  {
    id: 4,
    created_at: "2021-10-31T10:35:37",
    updated_at: "2020-02-15",
    name: "Melomakarono",
    description: "Egg shaped dessert made from olive oil, honey, cognac, cinnamon, orange.",
    price: 1100,
    in_stock: true,
    sale: false,
    category_id: 3,
    category_name: "general",
  },
  {
    id: 5,
    created_at: "2021-10-31T10:38:06",
    updated_at: "2020-02-15",
    name: "Galaktoboureko",
    description: "Dessert of semolina custard or rice custard in filo. Coated with a sweet syrup.",
    price: 1400,
    in_stock: true,
    sale: false,
    category_id: 3,
    category_name: "general",
  },
  {
    id: 6,
    created_at: "2021-10-31T10:38:55",
    updated_at: "2020-02-15",
    name: "Karydopita",
    description: "Dessert cake made primarily from walnuts and covered in a sweet syrup.",
    price: 1500,
    in_stock: true,
    sale: false,
    category_id: 3,
    category_name: "general",
  },
  {
    id: 7,
    created_at: "2021-10-31T10:39:24",
    updated_at: "2020-02-15",
    name: "Moussaka",
    description: "Layers of cooked aubergine slices alternating with minced meat, covered with a thick béchamel sauce.",
    price: 2300,
    in_stock: true,
    sale: false,
    category_id: 4,
    category_name: "general",
  },
  {
    id: 8,
    created_at: "2021-10-31T10:40:07",
    updated_at: "2020-02-15",
    name: "Roasted leg of lamb",
    description: "Slow roasted perfectly pink and juicy inside, covered with rosemary, garlic and honey.",
    price: 2200,
    in_stock: true,
    sale: false,
    category_id: 4,
    category_name: "general",
  },
  {
    id: 9,
    created_at: "2021-10-31T10:40:45",
    updated_at: "2020-02-15",
    name: "Chickpea soup",
    description: "Spicy full of herbs chickpeas soup made from olives, garlic, kale, bay leafs.",
    price: 1500,
    in_stock: true,
    sale: false,
    category_id: 4,
    category_name: "general",
  },
  {
    id: 10,
    created_at: "2021-10-31T10:44:36",
    updated_at: "2020-02-15",
    name: "Tabbouleh",
    description: "Vegetarian salad made mostly of finely chopped parsley, with tomatoes, mint, onion and bulgur.",
    price: 1100,
    in_stock: true,
    sale: false,
    category_id: 2,
    category_name: "general",
  },
  {
    id: 11,
    created_at: "2021-10-31T10:46:10",
    updated_at: "2020-02-15",
    name: "Octopus stifado",
    description: "Delightful stew made from octopus braised with wine, shallot onions, tomato, aromatic herb.",
    price: 1800,
    in_stock: true,
    sale: false,
    category_id: 4,
    category_name: "general",
  },
  {
    id: 12,
    created_at: "2021-10-31T10:51:23",
    updated_at: "2020-02-15",
    name: "Pita special",
    description: "Homemade pita bread filled with lettuce, pitted Kalamata olives, onion, roasted peppers and feta.",
    price: 900,
    in_stock: true,
    sale: false,
    category_id: 5,
    category_name: "general",
  },
  {
    id: 13,
    created_at: "2021-10-31T10:52:14",
    updated_at: "2020-02-15",
    name: "Horiatiki",
    description: "A truly traditional Greek Salad with ripe tomatoes, cucumbers, bell peppers, onions, and creamy feta",
    price: 850,
    in_stock: true,
    sale: false,
    category_id: 5,
    category_name: "general",
  },
]

export const appetizersMock = [
  {
    id: 1,
    created_at: "2021-10-31T08:57:59",
    updated_at: "2020-02-15",
    name: "Tzatziki",
    description: "Refreshing traditional cucumber and garlic yogourt dip. Seasoned with fresh, local herbs.",
    price: 850,
    in_stock: true,
    sale: false,
    category_id: 2,
    category_name: "general",
  },
  {
    id: 2,
    created_at: "2021-10-31T10:13:10",
    updated_at: "2020-02-15",
    name: "Keftedakia",
    description: "Bite size, beef or lamb meatballs seasoned with fresh Greek herbs.",
    price: 1600,
    in_stock: true,
    sale: false,
    category_id: 2,
    category_name: "general",
  },
  {
    id: 3,
    created_at: "2021-10-31T10:32:07",
    updated_at: "2020-02-15",
    name: "Saganaki",
    description: "Fried traditional Greek cheese - Graviera with light hint of lemon and garlic.",
    price: 1500,
    in_stock: true,
    sale: false,
    category_id: 2,
    category_name: "general",
  },
  {
    id: 10,
    created_at: "2021-10-31T10:44:36",
    updated_at: "2020-02-15",
    name: "Tabbouleh",
    description: "Vegetarian salad made mostly of finely chopped parsley, with tomatoes, mint, onion and bulgur.",
    price: 1100,
    in_stock: true,
    sale: false,
    category_id: 2,
    category_name: "general",
  },
]

export const saladsMock = [
  {
    id: 12,
    created_at: "2021-10-31T10:51:23",
    updated_at: "2020-02-15",
    name: "Pita special",
    description: "Homemade pita bread filled with lettuce, pitted Kalamata olives, onion, roasted peppers and feta.",
    price: 900,
    in_stock: true,
    sale: false,
    category_id: 5,
    category_name: "general",
  },
  {
    id: 13,
    created_at: "2021-10-31T10:52:14",
    updated_at: "2020-02-15",
    name: "Horiatiki",
    description: "A truly traditional Greek Salad with ripe tomatoes, cucumbers, bell peppers, onions, and creamy feta",
    price: 850,
    in_stock: true,
    sale: false,
    category_id: 5,
    category_name: "general",
  },
]
