export const fullProducts = [
  {
    __typename: "products",
    price: 850,
    name: "Tzatziki",
    id: 4,
    description: "Refreshing traditional cucumber and garlic yogurt dip. Seasoned with fresh, local herbs.",
    category_id: 2,
    category: { __typename: "categories", id: 2, name: "appetizers" },
  },
  {
    __typename: "products",
    price: 1600,
    name: "Keftedakia",
    id: 5,
    description: "Bite size, beef or lamb meatballs seasoned with fresh Greek herbs.",
    category_id: 2,
    category: { __typename: "categories", id: 2, name: "appetizers" },
  },
  {
    __typename: "products",
    price: 1500,
    name: "Saganaki",
    id: 6,
    description: "Fried traditional Greek cheese - Graviera with light hint of lemon and garlic.",
    category_id: 2,
    category: { __typename: "categories", id: 2, name: "appetizers" },
  },
  {
    __typename: "products",
    price: 1100,
    name: "Melomakarono",
    id: 7,
    description: "Egg shaped dessert made from olive oil, honey, cognac, cinnamon, orange.",
    category_id: 3,
    category: { __typename: "categories", id: 3, name: "desserts" },
  },
  {
    __typename: "products",
    price: 1400,
    name: "Galaktoboureko",
    id: 8,
    description: "Dessert of semolina custard or rice custard in filo. Coated with a sweet syrup.",
    category_id: 3,
    category: { __typename: "categories", id: 3, name: "desserts" },
  },
  {
    __typename: "products",
    price: 1500,
    name: "Karydopita",
    id: 9,
    description: "Dessert cake made primarily from walnuts and covered in a sweet syrup.",
    category_id: 3,
    category: { __typename: "categories", id: 3, name: "desserts" },
  },
  {
    __typename: "products",
    price: 2300,
    name: "Moussaka",
    id: 10,
    description: "Layers of cooked aubergine slices alternating with minced meat, covered with a thick béchamel sauce.",
    category_id: 4,
    category: { __typename: "categories", id: 4, name: "mains" },
  },
  {
    __typename: "products",
    price: 2200,
    name: "Roasted leg of lamb",
    id: 11,
    description: "Slow roasted perfectly pink and juicy inside, covered with rosemary, garlic and honey.",
    category_id: 4,
    category: { __typename: "categories", id: 4, name: "mains" },
  },
  {
    __typename: "products",
    price: 1500,
    name: "Chickpea soup",
    id: 12,
    description: "Spicy full of herbs chickpeas soup made from olives, garlic, kale, bay leafs.",
    category_id: 4,
    category: { __typename: "categories", id: 4, name: "mains" },
  },
  {
    __typename: "products",
    price: 1800,
    name: "Octopus stifado",
    id: 13,
    description: "Delightful stew made from octopus braised with wine, shallot onions, tomato, aromatic herb.",
    category_id: 4,
    category: { __typename: "categories", id: 4, name: "mains" },
  },
  {
    __typename: "products",
    price: 900,
    name: "Pita special",
    id: 14,
    description: "Homemade pita bread filled with lettuce, pitted Kalamata olives, onion, roasted peppers and feta.",
    category_id: 5,
    category: { __typename: "categories", id: 5, name: "salads" },
  },
  {
    __typename: "products",
    price: 850,
    name: "Horiatiki",
    id: 15,
    description: "A truly traditional Greek Salad with ripe tomatoes, cucumbers, bell peppers, onions, and creamy feta",
    category_id: 5,
    category: { __typename: "categories", id: 5, name: "salads" },
  },
  {
    __typename: "products",
    price: 1100,
    name: "Tabbouleh",
    id: 16,
    description: "Vegetarian salad made mostly of finely chopped parsley, with tomatoes, mint, onion and bulgur.",
    category_id: 2,
    category: { __typename: "categories", id: 2, name: "appetizers" },
  },
]

export const fullProductsSorted = {
  appetizers: [
    {
      __typename: "products",
      price: 850,
      name: "Tzatziki",
      id: 4,
      description: "Refreshing traditional cucumber and garlic yogurt dip. Seasoned with fresh, local herbs.",
      category_id: 2,
      category: { __typename: "categories", id: 2, name: "appetizers" },
    },
    {
      __typename: "products",
      price: 1600,
      name: "Keftedakia",
      id: 5,
      description: "Bite size, beef or lamb meatballs seasoned with fresh Greek herbs.",
      category_id: 2,
      category: { __typename: "categories", id: 2, name: "appetizers" },
    },
    {
      __typename: "products",
      price: 1500,
      name: "Saganaki",
      id: 6,
      description: "Fried traditional Greek cheese - Graviera with light hint of lemon and garlic.",
      category_id: 2,
      category: { __typename: "categories", id: 2, name: "appetizers" },
    },
    {
      __typename: "products",
      price: 1100,
      name: "Tabbouleh",
      id: 16,
      description: "Vegetarian salad made mostly of finely chopped parsley, with tomatoes, mint, onion and bulgur.",
      category_id: 2,
      category: { __typename: "categories", id: 2, name: "appetizers" },
    },
  ],
  desserts: [
    {
      __typename: "products",
      price: 1100,
      name: "Melomakarono",
      id: 7,
      description: "Egg shaped dessert made from olive oil, honey, cognac, cinnamon, orange.",
      category_id: 3,
      category: { __typename: "categories", id: 3, name: "desserts" },
    },
    {
      __typename: "products",
      price: 1400,
      name: "Galaktoboureko",
      id: 8,
      description: "Dessert of semolina custard or rice custard in filo. Coated with a sweet syrup.",
      category_id: 3,
      category: { __typename: "categories", id: 3, name: "desserts" },
    },
    {
      __typename: "products",
      price: 1500,
      name: "Karydopita",
      id: 9,
      description: "Dessert cake made primarily from walnuts and covered in a sweet syrup.",
      category_id: 3,
      category: { __typename: "categories", id: 3, name: "desserts" },
    },
  ],
  mains: [
    {
      __typename: "products",
      price: 2300,
      name: "Moussaka",
      id: 10,
      description:
        "Layers of cooked aubergine slices alternating with minced meat, covered with a thick béchamel sauce.",
      category_id: 4,
      category: { __typename: "categories", id: 4, name: "mains" },
    },
    {
      __typename: "products",
      price: 2200,
      name: "Roasted leg of lamb",
      id: 11,
      description: "Slow roasted perfectly pink and juicy inside, covered with rosemary, garlic and honey.",
      category_id: 4,
      category: { __typename: "categories", id: 4, name: "mains" },
    },
    {
      __typename: "products",
      price: 1500,
      name: "Chickpea soup",
      id: 12,
      description: "Spicy full of herbs chickpeas soup made from olives, garlic, kale, bay leafs.",
      category_id: 4,
      category: { __typename: "categories", id: 4, name: "mains" },
    },
    {
      __typename: "products",
      price: 1800,
      name: "Octopus stifado",
      id: 13,
      description: "Delightful stew made from octopus braised with wine, shallot onions, tomato, aromatic herb.",
      category_id: 4,
      category: { __typename: "categories", id: 4, name: "mains" },
    },
  ],
  salads: [
    {
      __typename: "products",
      price: 900,
      name: "Pita special",
      id: 14,
      description: "Homemade pita bread filled with lettuce, pitted Kalamata olives, onion, roasted peppers and feta.",
      category_id: 5,
      category: { __typename: "categories", id: 5, name: "salads" },
    },
    {
      __typename: "products",
      price: 850,
      name: "Horiatiki",
      id: 15,
      description:
        "A truly traditional Greek Salad with ripe tomatoes, cucumbers, bell peppers, onions, and creamy feta",
      category_id: 5,
      category: { __typename: "categories", id: 5, name: "salads" },
    },
  ],
  drinks: [],
}
